"use strict";

const GAME_WIDTH = 400;
const GAME_HEIGHT = 600;

const GRAVITY = 0.45;
const FLAP_STRENGTH = -7.5;
const BIRD_X = 80;
const BIRD_RADIUS = 15;

const PIPE_WIDTH = 55;
const PIPE_SPAWN_INTERVAL = 1600;
const PIPE_SPEED_BASE = 2.5;
const PIPE_SPEED_INCREMENT = 0.08;

const GAP_SIZE_BASE = 150;
const GAP_SIZE_MIN = 100;
const GAP_SHRINK_PER_5 = 4;

const GROUND_HEIGHT = 60;
const GROUND_Y = GAME_HEIGHT - GROUND_HEIGHT;

const PLAYER_MAX_HEALTH = 3;
const BULLET_SPEED = 12;
const BULLET_RADIUS = 5;
const BULLET_COOLDOWN = 200;

const ENEMY_SPAWN_INTERVAL = 3000;
const ENEMY_SPEED_BASE = 1.5;
const ENEMY_BULLET_SPEED = 4;
const ENEMY_FIRE_INTERVAL = 1500;
const ENEMY_RADIUS = 12;

const POWERUP_SPAWN_INTERVAL = 8000;
const POWERUP_RADIUS = 10;
const INVINCIBILITY_DURATION = 3000;
const MULTISHOT_DURATION = 5000;
const SCORE_MULTIPLIER_DURATION = 10000;
const INVINCIBILITY_FLASH_INTERVAL = 150;

const COLOR_SKY_TOP = "#4ec0ca";
const COLOR_SKY_BOTTOM = "#71c8d6";
const COLOR_GROUND = "#ded895";
const COLOR_GROUND_DARK = "#d2c56e";
const COLOR_PIPE = "#73bf2e";
const COLOR_PIPE_DARK = "#558b1f";
const COLOR_PIPE_CAP = "#5ea922";
const COLOR_BIRD_BODY = "#f5c842";
const COLOR_BIRD_BELLY = "#f7e076";
const COLOR_BIRD_WING = "#e6a817";
const COLOR_BIRD_BEAK = "#e8572a";
const COLOR_BIRD_EYE_WHITE = "#ffffff";
const COLOR_BIRD_EYE_PUPIL = "#333333";

const COLOR_PLAYER_BULLET = "#ffff00";
const COLOR_ENEMY = "#e74c3c";
const COLOR_ENEMY_BULLET = "#ff6b6b";
const COLOR_HEALTH_FULL = "#2ecc71";
const COLOR_HEALTH_EMPTY = "#95a5a6";
const COLOR_POWERUP_INVINCIBILITY = "#9b59b6";
const COLOR_POWERUP_MULTISHOT = "#f39c12";
const COLOR_POWERUP_MULTIPLIER = "#3498db";

const POWERUP_TYPES = {
  INVINCIBILITY: 0,
  MULTISHOT: 1,
  SCORE_MULTIPLIER: 2
};

const STATE = { READY: 0, PLAYING: 1, GAME_OVER: 2 };

module.exports = {
  GAME_WIDTH,
  GAME_HEIGHT,
  GRAVITY,
  FLAP_STRENGTH,
  BIRD_X,
  BIRD_RADIUS,
  PIPE_WIDTH,
  PIPE_SPAWN_INTERVAL,
  PIPE_SPEED_BASE,
  PIPE_SPEED_INCREMENT,
  GAP_SIZE_BASE,
  GAP_SIZE_MIN,
  GAP_SHRINK_PER_5,
  GROUND_HEIGHT,
  GROUND_Y,
  PLAYER_MAX_HEALTH,
  BULLET_SPEED,
  BULLET_RADIUS,
  BULLET_COOLDOWN,
  ENEMY_SPAWN_INTERVAL,
  ENEMY_SPEED_BASE,
  ENEMY_BULLET_SPEED,
  ENEMY_FIRE_INTERVAL,
  ENEMY_RADIUS,
  POWERUP_SPAWN_INTERVAL,
  POWERUP_RADIUS,
  INVINCIBILITY_DURATION,
  MULTISHOT_DURATION,
  SCORE_MULTIPLIER_DURATION,
  INVINCIBILITY_FLASH_INTERVAL,
  COLOR_SKY_TOP,
  COLOR_SKY_BOTTOM,
  COLOR_GROUND,
  COLOR_GROUND_DARK,
  COLOR_PIPE,
  COLOR_PIPE_DARK,
  COLOR_PIPE_CAP,
  COLOR_BIRD_BODY,
  COLOR_BIRD_BELLY,
  COLOR_BIRD_WING,
  COLOR_BIRD_BEAK,
  COLOR_BIRD_EYE_WHITE,
  COLOR_BIRD_EYE_PUPIL,
  COLOR_PLAYER_BULLET,
  COLOR_ENEMY,
  COLOR_ENEMY_BULLET,
  COLOR_HEALTH_FULL,
  COLOR_HEALTH_EMPTY,
  COLOR_POWERUP_INVINCIBILITY,
  COLOR_POWERUP_MULTISHOT,
  COLOR_POWERUP_MULTIPLIER,
  POWERUP_TYPES,
  STATE
};
